#!/bin/bash
set -euxo pipefail

# =============================================================================
# BudgetBot - EC2 User Data Bootstrap Script
# =============================================================================
# Script này tự động cài đặt và cấu hình môi trường cho BudgetBot
# trên EC2 instance (Amazon Linux 2023)
# =============================================================================

# Redirect tất cả output vào log file
exec > >(tee /var/log/budgetbot-setup.log) 2>&1
echo "=== BudgetBot bootstrap started at $(date) ==="

# ---- 1. Cập nhật hệ thống ----
dnf update -y

# ---- 2. Cài đặt Python 3.11, pip, git ----
dnf install -y python3.11 python3.11-pip git

# ---- 3. Tạo thư mục ứng dụng ----
mkdir -p /opt/budgetbot
cd /opt/budgetbot

# ---- 4. Tạo virtual environment ----
python3.11 -m venv /opt/budgetbot/venv
source /opt/budgetbot/venv/bin/activate

# ---- 5. Cài đặt dependencies ----
pip install --upgrade pip
pip install \
  fastapi==0.115.* \
  uvicorn[standard]==0.34.* \
  python-dotenv==1.1.* \
  pydantic==2.* \
  boto3==1.* \
  python-multipart==0.0.* \
  pymysql==1.*

# ---- 6. Tạo file cấu hình .env ----
cat > /opt/budgetbot/.env << 'ENVEOF'
# ============================================
# BudgetBot Environment Configuration
# Auto-generated by Terraform user_data
# ============================================

# ---- Application ----
APP_NAME=BudgetBot
SERVE_FRONTEND=true

# ---- AI Backend ----
AI_BACKEND=local

# ---- Storage Backend (S3) ----
STORAGE_BACKEND=s3
S3_BUCKET=${s3_bucket}
AWS_DEFAULT_REGION=${aws_region}

# ---- Database Backend (MySQL on RDS) ----
USERSTORE_BACKEND=mysql
MYSQL_HOST=${db_host}
MYSQL_PORT=${db_port}
MYSQL_DB=${db_name}
MYSQL_USER=${db_username}
MYSQL_PASSWORD=${db_password}
ENVEOF

# ---- 7. Tạo systemd service ----
cat > /etc/systemd/system/budgetbot.service << 'SVCEOF'
[Unit]
Description=BudgetBot Web Application
After=network.target

[Service]
Type=simple
User=ec2-user
WorkingDirectory=/opt/budgetbot
Environment=PATH=/opt/budgetbot/venv/bin:/usr/bin:/bin
EnvironmentFile=/opt/budgetbot/.env
ExecStart=/opt/budgetbot/venv/bin/uvicorn src.app:app --host 0.0.0.0 --port 80
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
SVCEOF

# ---- 8. Cấu hình quyền ----
chown -R ec2-user:ec2-user /opt/budgetbot

# ---- 9. Enable service (sẽ start sau khi deploy code) ----
systemctl daemon-reload
systemctl enable budgetbot.service

echo "=== BudgetBot bootstrap completed at $(date) ==="
echo "=== Deploy app code to /opt/budgetbot, then: sudo systemctl start budgetbot ==="
